### ISSUE TITLE
Hydration error

### ISSUE THREAD

**Issue by Aurion72** [ambitiondev/cookiebot#21]
Hello,

Im trying to use this package but i got an error : 

![image](https://github.com/user-attachments/assets/e1928bb0-df3e-4b2b-bed5-6cd79b826105)

I just installed the module and make a component : 

```
<template>
  <div></div>
</template>

<script setup lang="ts">
  const { consentBanner } = useCookiebot({})
  consentBanner()
</script>

```

nuxt.config.ts

```
cookiebot: {
    autoConsentBanner: false,
    cookieBotId: process.env.COOKIEBOT_ID,
  },

```

**Comment by bnachtweh** [comment]
Hi @Aurion72, thank you for your issue. Sadly I cannot reproduce your issue. Have you tried removing the module from Nuxt config to see if the problem persists? It seems like the mismatch is more on a templating level. The server renders an HTML comment regarding teleport, while the client renders a Nuxt layout. 

If the problem persists, can you please provide me with some more info, like:
- Are you running Nuxt 4 compatibility mode? (`future.compatibilityVersion` in Nuxt config file)
- Which version of Nuxt Cookiebot are you running?
- Which version of Nuxt are you running?

**Comment by Aurion72** [comment]
Thanks for your reply.

I've finally found the cause of the problem, it's nuxtUI's <UNotifications /> component which seems to conflict with your package or CookieBot itselft.

I couldn't say why, but I've wrapped <UNotifications /> in a <ClientOnly> and that seems to work.

https://github.com/nuxt/ui/blob/dev/src/runtime/components/overlays/Notifications.vue

**Comment by bnachtweh** [comment]
@Aurion72 it's probably due to the fact that you're rendering a separate component with an empty div into you document which has no other effect than injecting Cookiebot. The recommended usage is to either:

- remove the `autoConsentBanner` option, to let the module load the consent banner automatically (if you're not planning on adding additional settings to the composable, this is the recommended way)
- inject the composable and its `consentBanner` method directly inside the `app.vue` component:

```
// app.vue
<script setup lang="ts">
const { consentBanner } = useCookiebot({ 
  // config here, only if you're planning to override specifics
});

consentBanner();
</script>

<template>
  <div>
    <UContainer>
      <NuxtPage />
    </UContainer>

    <UNotifications />
  </div>
</template>
```

following either of those two solutions would solve your hydration error(s)
